name: CD

on:
  push:
    branches:
      - master

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v1
#      - name: npm install, build, and test
#        run: |
#          npm install
#          npm run build
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v1
#        with:
#          name: build
#          path: build
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: npm install, build, and test
        run: |
            npm install
            npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v1
        with:
          name: build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*' --exclude '.gitignore' --exclude 'README.md'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository
